# Generated by Django 4.1.6 on 2023-02-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_dish',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
                'db_table': 'category_dish',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe_dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('recipe', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auhtor', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.category_dish', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Рецепт блюда',
                'verbose_name_plural': 'Рецепты блюд',
                'db_table': 'recipe_dish',
                'ordering': ['published'],
            },
        ),
    ]
