# Generated by Django 4.1.6 on 2023-03-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDish',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Категория блюда')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL категории блюда')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
                'db_table': 'category_dish',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL название блюда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание блюда')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Список ингредиентов')),
                ('recipe', models.TextField(blank=True, null=True, verbose_name='Рецепт приготовления')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('auhtor', models.CharField(max_length=50, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение блюда')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.categorydish', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Рецепт блюда',
                'verbose_name_plural': 'Рецепты блюд',
                'db_table': 'recipe_dish',
                'ordering': ['published'],
            },
        ),
    ]
