# Generated by Django 4.1.6 on 2023-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание блюда'),
        ),
        migrations.AlterField(
            model_name='category_dish',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='recipe_dish',
            name='auhtor',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe_dish',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение блюда'),
        ),
        migrations.AlterField(
            model_name='recipe_dish',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe_dish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='recipe_dish',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipe_dish',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='Рецепт приготовления'),
        ),
    ]
